# Generated by Django 4.1 on 2022-08-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_color',
        ),
        migrations.AddField(
            model_name='profile',
            name='services',
            field=models.CharField(choices=[('NF', 'Netflix'), ('HU', 'Hulu'), ('HM', 'HBO Max'), ('AP', 'Amazon Prime')], default='NF', max_length=4),
        ),
    ]
