# Generated by Django 4.1 on 2022-08-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='services',
            field=models.ManyToManyField(to='main_app.service'),
        ),
    ]
