# Generated by Django 4.1 on 2022-08-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='pin',
            field=models.IntegerField(default=0),
        ),
    ]
